export const ACCESS_TOKEN_UPDATE = "ACCESS_TOKEN_UPDATE";
export type ACCESS_TOKEN_UPDATE = typeof ACCESS_TOKEN_UPDATE;

export const MOODLE_TOKEN_UPDATE = "MOODLE_TOKEN_UPDATE";
export type MOODLE_TOKEN_UPDATE = typeof MOODLE_TOKEN_UPDATE;

export const LOCALE_UPDATE = "LOCALE_UPDATE";
export type LOCALE_UPDATE = typeof LOCALE_UPDATE;
